backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"

collections:
  - name: "episodes"
    label: "Episodes" 
    folder: "_posts/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "string", required: true, default: "episode" }
      - { label: "Episode Number", name: "number", widget: "number", required: true }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Tags", name: "tags", widget: "list", required: true }
      - label: 'Readings'
        name: 'readings'
        widget: 'list'
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string", required: true }
          - { label: "Author", name: "author", widget: "string", required: true }
          - { label: "Year", name: "year", widget: "string", required: false }
          - { label: "Type", name: "type", widget: "string", required: true }
          - { label: "Url", name: "url", widget: "string", required: true }
      - label: "Discussion Questions"
        name: "discussionQuestions"
        widget: "list"
        required: true
        fields:
          - { label: "Question", name: "question", widget: "string", required: true }
      - {label: "Spotify Link", name: "spotifyLink", widget: "string", required: false }
      - { label: "Apple Link", name: "appleLink", widget: "string", required: true }
      - { label: "Audio Link", name: "audioLink", widget: "string", required: true }
      - { label : "Image", name: "image", widget: "image", required: false }
      - { label: "Has Transcript", name: "hasTranscript", widget: "boolean", required: true }
      - { label: "Transcript", name: "transcript", widget: "text", required: false }